# Generated by Django 5.2.1 on 2025-05-27 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='date started')),
                ('start_time', models.TimeField(verbose_name='time started')),
                ('end_time', models.TimeField(verbose_name='time ended')),
                ('player_spaces', models.IntegerField()),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='players.organizer')),
            ],
        ),
    ]
