# Generated by Django 5.2.1 on 2025-05-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='date started')),
                ('start_time', models.TimeField(verbose_name='time started')),
                ('player_spaces', models.IntegerField()),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prizes', models.TextField()),
            ],
        ),
    ]
