# Generated by Django 5.2.1 on 2025-05-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='date started')),
                ('start_time', models.TimeField(verbose_name='time started')),
                ('end_time', models.TimeField(verbose_name='time ended')),
                ('player_spaces', models.IntegerField()),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='game_name',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='player_spaces',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_time',
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
