# Generated by Django 5.2.1 on 2025-05-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_remove_tournament_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
