# Generated by Django 5.2.1 on 2025-07-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="preferred_game",
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
